Repository LucasPeixer/library-go-api-rest, pull requests merged in 2024-11, with the labels that each got.

#3 Allow usage of .env file
  .env.example
  .gitignore
  cmd/main.go
  go.mod
  go.sum
  initializers/load_env.go
Labels: enhancement

#4 Updates the README.md file
  README.md
Labels: documentation

#5 Update DDL to represent new changes of the database
  ddl.sql
Labels: enhancement

#6 Adiciona rotas de gerenciamento de estoque de livro e atualiza rotas de livro
  cmd/create-user.go
  controller/book_controller.go
  model/book.go
  model/book_stock.go
  repository/book_repository.go
  routes/book_routes.go
  usecase/book_usecase.go
Labels: enhancement

#8 Tabela de estoque de livro + rotas
  cmd/create-user.go
  controller/book_controller.go
  model/book.go
  model/book_stock.go
  repository/book_repository.go
  routes/book_routes.go
  usecase/book_usecase.go
Labels: enhancement

#9 Adiciona rotas para listar usuários
  controller/user_controller.go
  repository/user_repository.go
  routes/user_routes.go
  usecase/user_usecase.go
Labels: enhancement

#11 Adiciona rotas para ativar/desativar e excluir um usuário
  controller/user_controller.go
  repository/user_repository.go
  routes/user_routes.go
  usecase/user_usecase.go
Labels: enhancement

#13 Corrige três problemas do DDL do banco
  ddl.sql
Labels: bug

#14 Adiciona rota para buscar livro por Id
  controller/book_controller.go
  repository/book_repository.go
  routes/book_routes.go
  usecase/book_usecase.go
Labels: enhancement

#15 Corrige rota de estoque que não recebia ID
  controller/book_controller.go
  repository/book_repository.go
  routes/book_routes.go
  usecase/book_usecase.go
Labels: bug

#17 Feat/add get user loan
  controller/user_controller.go
  model/loan.go
  repository/user_repository.go
  routes/user_routes.go
  usecase/user_usecase.go
Labels: enhancement

#20 Adiciona coluna de CPF
  cmd/create-user.go
  controller/user_controller.go
  ddl.sql
  docs/swagger.json
  model/user/account.go
  repository/user_repository.go
  usecase/user_usecase.go
  utils/validator.go
Labels: enhancement

#21 Feat/add get user reservation
  repository/user_repository.go
  usecase/reservation_usecase.go
  usecase/user_usecase.go
Labels: enhancement

#24 Retorna o Id do usuário quando registrado
  controller/user_controller.go
  repository/user_repository.go
  usecase/user_usecase.go
Labels: enhancement

#12 Feat/create book reservation
  controller/reservation_controller.go
  model/reservation.go
  repository/reservation_repository.go
  routes/reservation_routes.go
  usecase/reservation_usecase.go
Labels: enhancement

#22 Decrementa a quantidade de reservas pendentes na quantidade de livros disponíveis
  repository/book_repository.go
Labels: bug

#23 Impede exclusão de estoque de livro com reservas ativas
  ddl.sql
Labels: enhancement

#25 Adiciona retorno do Id do livro do estoque
  controller/book_controller.go
Labels: enhancement

#29 Adiciona rotas de busca de reserva por usuário e cancelamento de reserva por usuário
  controller/user_controller.go
  repository/user_repository.go
  routes/user_routes.go
  usecase/user_usecase.go
Labels: enhancement

#31 Remove parâmetro 'book_codes' da rota books/create
  controller/book_controller.go
  docs/swagger.json
  repository/book_repository.go
  usecase/book_usecase.go
Labels: bug

#36 Corrige a quantidade incorreta de livros sendo retornados em Amount
  repository/book_repository.go
  repository/reservation_repository.go
  routes/book_routes.go
  usecase/book_usecase.go
Labels: bug

#47 Corrige o problema de não conseguir criar uma reserva por causa de estoque
  usecase/book_usecase.go
  usecase/reservation_usecase.go
Labels: bug

#46 Implementa função para atualizar estado do livro
  controller/book_controller.go
  ddl.sql
  model/book_stock.go
  usecase/book_usecase.go
Labels: enhancement

#44 Atualiza praticamente todo o Swagger
  docs/swagger.json
Labels: documentation, enhancement
